services:
  gokapi:
    build: .
    container_name: gokapi
    restart: unless-stopped
    ports:
      - "9001:53842"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./custom:/app/custom
